language: csharp
dotnet: 2.0.0
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=true
mono:
 - latest
matrix:
  include:
    - os: linux
      dist: trusty      
      sudo: false
    - os: osx
      osx_image: xcode9      
      sudo: required               
script:  
  - ulimit -n8192  
  - chmod +x build.sh
  - ./build.sh