version: 1.0.{build}
image: Visual Studio 2017
build_script:
- ps: >-
    cd .\build\

    .\install-dotnet-script.ps1
- cmd:
    dotnet .\dotnet-script\dotnet-script.dll build.csx

test: off
artifacts:
- path: /**/Dotnet.Script*.nupkg
  name: Chocolatey Packages
# Uncomment this to enable deploy on repo tagging
# deploy:
#   provider: Chocolatey  
#   api_key:
#     secure: [Your API key goes here]
#   skip_symbols: false  
#   artifact: /.*\.nupkg/
#   on:
#     appveyor_repo_tag: true