version: 1.0.{build}
image: Visual Studio 2017

install:
- cmd: choco install dotnet.script

build_script:
- cmd: >-
    cd build

    refreshenv

    dotnet script build.csx

artifacts:
- path: build\Artifacts\Chocolatey\*.nupgk
  name: Chocolatey Packages

- path: build\Artifacts\NuGet\*.nupgk
  name: NuGet Packages

- path: build\Artifacts\GitHub\*.zip
  name: GitHub  

test: off
environment:
    IS_SECURE_BUILDENVIRONM∥ENT:
        secure: The encoded value of 'true' (not including the apostrophes)
    GITHUB_REPO_TOKEN:
        secure: The encoded value of your GitHub Access Token.
    NUGET_APIKEY:
        secure: The encoded value of your NuGet ApiKey.
    CHOCO_APIKEY:
        secure: The encoded value of the Choco API Key (dotnet-script account).